minor changes in the About page
BitByte-TPC/hackbyte pull request #55
Opened 2024-02-08 20:31 UTC by Kushdapush

made some ui changes in the about page

2024-02-08 20:36 UTC, mittalvansh requested changes

2024-02-08 20:36 UTC, mittalvansh commented on public/aboutPage/AboutPageImage1.jpg
Convert the image to WebP format and apply compression to enhance its file size optimization.

2024-02-08 20:36 UTC, mittalvansh commented on app/about/page.jsx
Here, use next/Image for img

2024-02-08 21:23 UTC, Kushdapush commented on app/about/page.jsx
Hey @mittalvansh PTAL

2024-02-09 09:50 UTC, mittalvansh commented
@Kushdapush solve merge conflicts

2024-02-09 16:49 UTC, mittalvansh approved these changes

2024-02-09 16:50 UTC, merged