Added sitemap and robots.txt file to improve SEO.
BitByte-TPC/hackbyte pull request #62
Opened 2024-02-17 18:02 UTC by Pratik2026

This PR includes the following additions  to improve the SEO :

- XML Sitemap : to indicate the URLs and timestamps of recent updates of specific pages.
- Robots.txt : to provide instructions to crawlers about indexing the pages.

2024-02-17 18:11 UTC, mittalvansh requested changes

2024-02-17 18:11 UTC, mittalvansh commented on public/sitemap.xml
Consider adding priority for each page in the sitemap. The priority tag can help search engines understand the relative importance of different pages.

2024-02-17 18:35 UTC, Pratik2026 commented on public/sitemap.xml
I have added the priority for each page

2024-02-18 10:22 UTC, mittalvansh approved these changes

2024-02-18 10:22 UTC, merged